/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CompradorRouteImport } from './routes/comprador'
import { Route as EsqueciMinhaSenhaRouteImport } from './routes/esqueci-minha-senha'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OperacaoRouteImport } from './routes/operacao'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as VistoriaRouteImport } from './routes/vistoria'
import { Route as OperacaoLeadsRouteImport } from './routes/operacao/leads'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CompradorRoute = CompradorRouteImport.update({
  id: '/comprador',
  path: '/comprador',
  getParentRoute: () => rootRouteImport,
} as any)
const EsqueciMinhaSenhaRoute = EsqueciMinhaSenhaRouteImport.update({
  id: '/esqueci-minha-senha',
  path: '/esqueci-minha-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OperacaoRoute = OperacaoRouteImport.update({
  id: '/operacao',
  path: '/operacao',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const VistoriaRoute = VistoriaRouteImport.update({
  id: '/vistoria',
  path: '/vistoria',
  getParentRoute: () => rootRouteImport,
} as any)
const OperacaoLeadsRoute = OperacaoLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => OperacaoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/comprador': typeof CompradorRoute
  '/esqueci-minha-senha': typeof EsqueciMinhaSenhaRoute
  '/login': typeof LoginRoute
  '/operacao': typeof OperacaoRouteWithChildren
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/vistoria': typeof VistoriaRoute
  '/operacao/leads': typeof OperacaoLeadsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/comprador': typeof CompradorRoute
  '/esqueci-minha-senha': typeof EsqueciMinhaSenhaRoute
  '/login': typeof LoginRoute
  '/operacao': typeof OperacaoRouteWithChildren
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/vistoria': typeof VistoriaRoute
  '/operacao/leads': typeof OperacaoLeadsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/comprador': typeof CompradorRoute
  '/esqueci-minha-senha': typeof EsqueciMinhaSenhaRoute
  '/login': typeof LoginRoute
  '/operacao': typeof OperacaoRouteWithChildren
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/vistoria': typeof VistoriaRoute
  '/operacao/leads': typeof OperacaoLeadsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/comprador'
    | '/esqueci-minha-senha'
    | '/login'
    | '/operacao'
    | '/redefinir-senha'
    | '/vistoria'
    | '/operacao/leads'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/comprador'
    | '/esqueci-minha-senha'
    | '/login'
    | '/operacao'
    | '/redefinir-senha'
    | '/vistoria'
    | '/operacao/leads'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/comprador'
    | '/esqueci-minha-senha'
    | '/login'
    | '/operacao'
    | '/redefinir-senha'
    | '/vistoria'
    | '/operacao/leads'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CompradorRoute: typeof CompradorRoute
  EsqueciMinhaSenhaRoute: typeof EsqueciMinhaSenhaRoute
  LoginRoute: typeof LoginRoute
  OperacaoRoute: typeof OperacaoRouteWithChildren
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  VistoriaRoute: typeof VistoriaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comprador': {
      id: '/comprador'
      path: '/comprador'
      fullPath: '/comprador'
      preLoaderRoute: typeof CompradorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esqueci-minha-senha': {
      id: '/esqueci-minha-senha'
      path: '/esqueci-minha-senha'
      fullPath: '/esqueci-minha-senha'
      preLoaderRoute: typeof EsqueciMinhaSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operacao': {
      id: '/operacao'
      path: '/operacao'
      fullPath: '/operacao'
      preLoaderRoute: typeof OperacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vistoria': {
      id: '/vistoria'
      path: '/vistoria'
      fullPath: '/vistoria'
      preLoaderRoute: typeof VistoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operacao/leads': {
      id: '/operacao/leads'
      path: '/leads'
      fullPath: '/operacao/leads'
      preLoaderRoute: typeof OperacaoLeadsRouteImport
      parentRoute: typeof OperacaoRoute
    }
  }
}

interface OperacaoRouteChildren {
  OperacaoLeadsRoute: typeof OperacaoLeadsRoute
}

const OperacaoRouteChildren: OperacaoRouteChildren = {
  OperacaoLeadsRoute: OperacaoLeadsRoute,
}

const OperacaoRouteWithChildren = OperacaoRoute._addFileChildren(
  OperacaoRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CompradorRoute: CompradorRoute,
  EsqueciMinhaSenhaRoute: EsqueciMinhaSenhaRoute,
  LoginRoute: LoginRoute,
  OperacaoRoute: OperacaoRouteWithChildren,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  VistoriaRoute: VistoriaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
